package com.tap2up.pojo;

public class AlfUserLibrary {

    private Integer id;


    private String userid;


    private String devicesn;


    private String modelversion;


    private Long timestamp;


    private String avatarid;


    private Integer companyid;


    private String feature;


    private String icnumber;


    private String idnumber;


    private Integer type;


    private Long createat;


    private Long userupdatedat;


    private String username;


    private String birthday;


    private String prompt;


    private Integer permission;


    private Integer groupid;


    private String groupname;


    private String signavatar;


    private String signbgavatar;


    private Long uservalidstarttime;


    private Long uservalidendtime;


    private String token;


    private String sign;


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary._id
     *
     * @param id the value for alfuserlibrary._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.userId
     *
     * @return the value of alfuserlibrary.userId
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.userId
     *
     * @param userid the value for alfuserlibrary.userId
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.deviceSn
     *
     * @return the value of alfuserlibrary.deviceSn
     *
     * @mbg.generated
     */
    public String getDevicesn() {
        return devicesn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.deviceSn
     *
     * @param devicesn the value for alfuserlibrary.deviceSn
     *
     * @mbg.generated
     */
    public void setDevicesn(String devicesn) {
        this.devicesn = devicesn == null ? null : devicesn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.modelVersion
     *
     * @return the value of alfuserlibrary.modelVersion
     *
     * @mbg.generated
     */
    public String getModelversion() {
        return modelversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.modelVersion
     *
     * @param modelversion the value for alfuserlibrary.modelVersion
     *
     * @mbg.generated
     */
    public void setModelversion(String modelversion) {
        this.modelversion = modelversion == null ? null : modelversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.timestamp
     *
     * @return the value of alfuserlibrary.timestamp
     *
     * @mbg.generated
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.timestamp
     *
     * @param timestamp the value for alfuserlibrary.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.avatarId
     *
     * @return the value of alfuserlibrary.avatarId
     *
     * @mbg.generated
     */
    public String getAvatarid() {
        return avatarid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.avatarId
     *
     * @param avatarid the value for alfuserlibrary.avatarId
     *
     * @mbg.generated
     */
    public void setAvatarid(String avatarid) {
        this.avatarid = avatarid == null ? null : avatarid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.companyId
     *
     * @return the value of alfuserlibrary.companyId
     *
     * @mbg.generated
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.companyId
     *
     * @param companyid the value for alfuserlibrary.companyId
     *
     * @mbg.generated
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.feature
     *
     * @return the value of alfuserlibrary.feature
     *
     * @mbg.generated
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.feature
     *
     * @param feature the value for alfuserlibrary.feature
     *
     * @mbg.generated
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.icNumber
     *
     * @return the value of alfuserlibrary.icNumber
     *
     * @mbg.generated
     */
    public String getIcnumber() {
        return icnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.icNumber
     *
     * @param icnumber the value for alfuserlibrary.icNumber
     *
     * @mbg.generated
     */
    public void setIcnumber(String icnumber) {
        this.icnumber = icnumber == null ? null : icnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.idNumber
     *
     * @return the value of alfuserlibrary.idNumber
     *
     * @mbg.generated
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.idNumber
     *
     * @param idnumber the value for alfuserlibrary.idNumber
     *
     * @mbg.generated
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.type
     *
     * @return the value of alfuserlibrary.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.type
     *
     * @param type the value for alfuserlibrary.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.createAt
     *
     * @return the value of alfuserlibrary.createAt
     *
     * @mbg.generated
     */
    public Long getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.createAt
     *
     * @param createat the value for alfuserlibrary.createAt
     *
     * @mbg.generated
     */
    public void setCreateat(Long createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.userUpdatedAt
     *
     * @return the value of alfuserlibrary.userUpdatedAt
     *
     * @mbg.generated
     */
    public Long getUserupdatedat() {
        return userupdatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.userUpdatedAt
     *
     * @param userupdatedat the value for alfuserlibrary.userUpdatedAt
     *
     * @mbg.generated
     */
    public void setUserupdatedat(Long userupdatedat) {
        this.userupdatedat = userupdatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.userName
     *
     * @return the value of alfuserlibrary.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.userName
     *
     * @param username the value for alfuserlibrary.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.birthDay
     *
     * @return the value of alfuserlibrary.birthDay
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.birthDay
     *
     * @param birthday the value for alfuserlibrary.birthDay
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.prompt
     *
     * @return the value of alfuserlibrary.prompt
     *
     * @mbg.generated
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.prompt
     *
     * @param prompt the value for alfuserlibrary.prompt
     *
     * @mbg.generated
     */
    public void setPrompt(String prompt) {
        this.prompt = prompt == null ? null : prompt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.permission
     *
     * @return the value of alfuserlibrary.permission
     *
     * @mbg.generated
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.permission
     *
     * @param permission the value for alfuserlibrary.permission
     *
     * @mbg.generated
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.groupId
     *
     * @return the value of alfuserlibrary.groupId
     *
     * @mbg.generated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.groupId
     *
     * @param groupid the value for alfuserlibrary.groupId
     *
     * @mbg.generated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.groupName
     *
     * @return the value of alfuserlibrary.groupName
     *
     * @mbg.generated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.groupName
     *
     * @param groupname the value for alfuserlibrary.groupName
     *
     * @mbg.generated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.signAvatar
     *
     * @return the value of alfuserlibrary.signAvatar
     *
     * @mbg.generated
     */
    public String getSignavatar() {
        return signavatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.signAvatar
     *
     * @param signavatar the value for alfuserlibrary.signAvatar
     *
     * @mbg.generated
     */
    public void setSignavatar(String signavatar) {
        this.signavatar = signavatar == null ? null : signavatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.signBgAvatar
     *
     * @return the value of alfuserlibrary.signBgAvatar
     *
     * @mbg.generated
     */
    public String getSignbgavatar() {
        return signbgavatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.signBgAvatar
     *
     * @param signbgavatar the value for alfuserlibrary.signBgAvatar
     *
     * @mbg.generated
     */
    public void setSignbgavatar(String signbgavatar) {
        this.signbgavatar = signbgavatar == null ? null : signbgavatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.userValidStartTime
     *
     * @return the value of alfuserlibrary.userValidStartTime
     *
     * @mbg.generated
     */
    public Long getUservalidstarttime() {
        return uservalidstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.userValidStartTime
     *
     * @param uservalidstarttime the value for alfuserlibrary.userValidStartTime
     *
     * @mbg.generated
     */
    public void setUservalidstarttime(Long uservalidstarttime) {
        this.uservalidstarttime = uservalidstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.userValidEndTime
     *
     * @return the value of alfuserlibrary.userValidEndTime
     *
     * @mbg.generated
     */
    public Long getUservalidendtime() {
        return uservalidendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.userValidEndTime
     *
     * @param uservalidendtime the value for alfuserlibrary.userValidEndTime
     *
     * @mbg.generated
     */
    public void setUservalidendtime(Long uservalidendtime) {
        this.uservalidendtime = uservalidendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.token
     *
     * @return the value of alfuserlibrary.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.token
     *
     * @param token the value for alfuserlibrary.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alfuserlibrary.sign
     *
     * @return the value of alfuserlibrary.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alfuserlibrary.sign
     *
     * @param sign the value for alfuserlibrary.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }
}