package com.tap2up.pojo;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.mid
     *
     * @mbg.generated
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.ctime
     *
     * @mbg.generated
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.updatatime
     *
     * @mbg.generated
     */
    private Long updatatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.isdelete
     *
     * @mbg.generated
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image._id
     *
     * @return the value of image._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image._id
     *
     * @param id the value for image._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.mid
     *
     * @return the value of image.mid
     *
     * @mbg.generated
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.mid
     *
     * @param mid the value for image.mid
     *
     * @mbg.generated
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.path
     *
     * @return the value of image.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.path
     *
     * @param path the value for image.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.type
     *
     * @return the value of image.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.type
     *
     * @param type the value for image.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.ctime
     *
     * @return the value of image.ctime
     *
     * @mbg.generated
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.ctime
     *
     * @param ctime the value for image.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.updatatime
     *
     * @return the value of image.updatatime
     *
     * @mbg.generated
     */
    public Long getUpdatatime() {
        return updatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.updatatime
     *
     * @param updatatime the value for image.updatatime
     *
     * @mbg.generated
     */
    public void setUpdatatime(Long updatatime) {
        this.updatatime = updatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.isdelete
     *
     * @return the value of image.isdelete
     *
     * @mbg.generated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.isdelete
     *
     * @param isdelete the value for image.isdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}