package com.tap2up.pojo;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.companyId
     *
     * @mbg.generated
     */
    private Integer companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.deviceSn
     *
     * @mbg.generated
     */
    private String devicesn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.groupId
     *
     * @mbg.generated
     */
    private Integer groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.groupName
     *
     * @mbg.generated
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.signAvatar
     *
     * @mbg.generated
     */
    private String signavatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.signBgAvatar
     *
     * @mbg.generated
     */
    private String signbgavatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.signTime
     *
     * @mbg.generated
     */
    private String signtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.oneOne
     *
     * @mbg.generated
     */
    private Double oneone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.oneN
     *
     * @mbg.generated
     */
    private Double onen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.mode
     *
     * @mbg.generated
     */
    private Integer mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.idNumber
     *
     * @mbg.generated
     */
    private String idnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.idInfo
     *
     * @mbg.generated
     */
    private String idinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.icNumber
     *
     * @mbg.generated
     */
    private String icnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.timestamp
     *
     * @mbg.generated
     */
    private Long timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record._id
     *
     * @return the value of record._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record._id
     *
     * @param id the value for record._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.companyId
     *
     * @return the value of record.companyId
     *
     * @mbg.generated
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.companyId
     *
     * @param companyid the value for record.companyId
     *
     * @mbg.generated
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.deviceSn
     *
     * @return the value of record.deviceSn
     *
     * @mbg.generated
     */
    public String getDevicesn() {
        return devicesn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.deviceSn
     *
     * @param devicesn the value for record.deviceSn
     *
     * @mbg.generated
     */
    public void setDevicesn(String devicesn) {
        this.devicesn = devicesn == null ? null : devicesn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.groupId
     *
     * @return the value of record.groupId
     *
     * @mbg.generated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.groupId
     *
     * @param groupid the value for record.groupId
     *
     * @mbg.generated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.userName
     *
     * @return the value of record.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.userName
     *
     * @param username the value for record.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.groupName
     *
     * @return the value of record.groupName
     *
     * @mbg.generated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.groupName
     *
     * @param groupname the value for record.groupName
     *
     * @mbg.generated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.signAvatar
     *
     * @return the value of record.signAvatar
     *
     * @mbg.generated
     */
    public String getSignavatar() {
        return signavatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.signAvatar
     *
     * @param signavatar the value for record.signAvatar
     *
     * @mbg.generated
     */
    public void setSignavatar(String signavatar) {
        this.signavatar = signavatar == null ? null : signavatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.signBgAvatar
     *
     * @return the value of record.signBgAvatar
     *
     * @mbg.generated
     */
    public String getSignbgavatar() {
        return signbgavatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.signBgAvatar
     *
     * @param signbgavatar the value for record.signBgAvatar
     *
     * @mbg.generated
     */
    public void setSignbgavatar(String signbgavatar) {
        this.signbgavatar = signbgavatar == null ? null : signbgavatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.signTime
     *
     * @return the value of record.signTime
     *
     * @mbg.generated
     */
    public String getSigntime() {
        return signtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.signTime
     *
     * @param signtime the value for record.signTime
     *
     * @mbg.generated
     */
    public void setSigntime(String signtime) {
        this.signtime = signtime == null ? null : signtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.oneOne
     *
     * @return the value of record.oneOne
     *
     * @mbg.generated
     */
    public Double getOneone() {
        return oneone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.oneOne
     *
     * @param oneone the value for record.oneOne
     *
     * @mbg.generated
     */
    public void setOneone(Double oneone) {
        this.oneone = oneone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.oneN
     *
     * @return the value of record.oneN
     *
     * @mbg.generated
     */
    public Double getOnen() {
        return onen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.oneN
     *
     * @param onen the value for record.oneN
     *
     * @mbg.generated
     */
    public void setOnen(Double onen) {
        this.onen = onen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.mode
     *
     * @return the value of record.mode
     *
     * @mbg.generated
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.mode
     *
     * @param mode the value for record.mode
     *
     * @mbg.generated
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.type
     *
     * @return the value of record.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.type
     *
     * @param type the value for record.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.idNumber
     *
     * @return the value of record.idNumber
     *
     * @mbg.generated
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.idNumber
     *
     * @param idnumber the value for record.idNumber
     *
     * @mbg.generated
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.idInfo
     *
     * @return the value of record.idInfo
     *
     * @mbg.generated
     */
    public String getIdinfo() {
        return idinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.idInfo
     *
     * @param idinfo the value for record.idInfo
     *
     * @mbg.generated
     */
    public void setIdinfo(String idinfo) {
        this.idinfo = idinfo == null ? null : idinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.icNumber
     *
     * @return the value of record.icNumber
     *
     * @mbg.generated
     */
    public String getIcnumber() {
        return icnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.icNumber
     *
     * @param icnumber the value for record.icNumber
     *
     * @mbg.generated
     */
    public void setIcnumber(String icnumber) {
        this.icnumber = icnumber == null ? null : icnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.timestamp
     *
     * @return the value of record.timestamp
     *
     * @mbg.generated
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.timestamp
     *
     * @param timestamp the value for record.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.token
     *
     * @return the value of record.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.token
     *
     * @param token the value for record.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.sign
     *
     * @return the value of record.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.sign
     *
     * @param sign the value for record.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }
}