package com.tap2up.pojo;

import java.util.Arrays;

public class UserInfo {
    @Override
    public String toString() {
        return "UserInfo{" +
                "id=" + id +
                ", userId='" + userId + '\'' +
                ", userName='" + userName + '\'' +
                ", groupId='" + groupId + '\'' +
                ", faceToken='" + faceToken + '\'' +
                ", imageName='" + imageName + '\'' +
                ", ctime=" + ctime +
                ", updateTime=" + updateTime +
                ", feature=" + Arrays.toString(feature) +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.group_id
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.face_token
     *
     * @mbg.generated
     */
    private String faceToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.image_name
     *
     * @mbg.generated
     */
    private String imageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ctime
     *
     * @mbg.generated
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.feature
     *
     * @mbg.generated
     */
    private byte[] feature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo._id
     *
     * @return the value of userinfo._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo._id
     *
     * @param id the value for userinfo._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_id
     *
     * @return the value of userinfo.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_id
     *
     * @param userId the value for userinfo.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_name
     *
     * @return the value of userinfo.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_name
     *
     * @param userName the value for userinfo.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.group_id
     *
     * @return the value of userinfo.group_id
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.group_id
     *
     * @param groupId the value for userinfo.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.face_token
     *
     * @return the value of userinfo.face_token
     *
     * @mbg.generated
     */
    public String getFaceToken() {
        return faceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.face_token
     *
     * @param faceToken the value for userinfo.face_token
     *
     * @mbg.generated
     */
    public void setFaceToken(String faceToken) {
        this.faceToken = faceToken == null ? null : faceToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.image_name
     *
     * @return the value of userinfo.image_name
     *
     * @mbg.generated
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.image_name
     *
     * @param imageName the value for userinfo.image_name
     *
     * @mbg.generated
     */
    public void setImageName(String imageName) {
        this.imageName = imageName == null ? null : imageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.ctime
     *
     * @return the value of userinfo.ctime
     *
     * @mbg.generated
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.ctime
     *
     * @param ctime the value for userinfo.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.update_time
     *
     * @return the value of userinfo.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.update_time
     *
     * @param updateTime the value for userinfo.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.feature
     *
     * @return the value of userinfo.feature
     *
     * @mbg.generated
     */
    public byte[] getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.feature
     *
     * @param feature the value for userinfo.feature
     *
     * @mbg.generated
     */
    public void setFeature(byte[] feature) {
        this.feature = feature;
    }
}