package com.tap2up.mapper;

import com.tap2up.pojo.AlfUserLibrary;

import java.util.Map;

public interface AlfUserLibraryMapper {


    public Map getUserStatistics();
    public AlfUserLibrary getAlfUserLibrarybyUserId(Integer userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alfuserlibrary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alfuserlibrary
     *
     * @mbg.generated
     */
    int insert(AlfUserLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alfuserlibrary
     *
     * @mbg.generated
     */
    int insertSelective(AlfUserLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alfuserlibrary
     *
     * @mbg.generated
     */
    AlfUserLibrary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alfuserlibrary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AlfUserLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alfuserlibrary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AlfUserLibrary record);
}